### PR TITLE
Works with other packages

### LINKED ISSUE #10: add other installed packages
you can implement to load 'snippets' of other installed packages?

### PR DESCRIPTION
**Pull request by jonathandelgado**
This fixes #10 

As mentioned in that issue, the loading system is outdated; this approach grabs all snippets for the current scope, just as the native snippets package does.

As per the tests, I updated them to reflect the changes. I removed the fixture for the outdated loading system, but kept and updated the visual tests.

On a side note, this is still not 100% on par with the snippet package in terms of matching. For example, the snippet `@param` will not work, because of the at symbol. The `@prefixOfSelection` function from autocomplete-plus either needs to be rewritten locally or in that repo so it can match non `[a-zA-Z]` characters. It looks like #18 was an attempt at fixing this, but was a little awkward.

### CODE REVIEW

**Comment by jonathandelgado** [comment]
Just spent a few minutes trying to figure out why the tests weren't working; two things:

- The path to the `sample.js` fixture was actually never correct, so the scope wasn't initially working
- Once I fixed that, I noticed the spec inserts a `entity.name.type.object.js.firebug` scope ontop of the normal javascript, which is hindering the scope detection.

I looked how the native snippets package handles tests, but they literally just inject the scope
https://github.com/atom/snippets/blob/e219deee67b8f1dd89a71927ddb4d3343da09bda/spec/snippet-loading-spec.coffee#L38

Let me know how you would like to proceed?

**Comment by joefitzgerald** [comment]
Is it possible that for a given cursor position there are multiple scopes? It would be best if the snippets were collected for each scope down the tree of scopes (where applicable)...

**Comment by jonathandelgado** [comment]
@joefitzgerald That is exactly how it works. I took the code from the native snippets package, see:

https://github.com/atom/snippets/blob/e219deee67b8f1dd89a71927ddb4d3343da09bda/lib/snippets.coffee#L201

`.getScopeDescriptor()` returns an array of scopes. In your snippet file, you can specify things like `source.js comment.block` to only make a snippet applicable to a javascript comment block. If your question was in reference to the tests not working, the default snippets don't have the `entity.name.type.object.js.firebug` scope included, which causes them to be excluded.

**Comment by jonathandelgado** [comment]
@joefitzgerald bump?

**Pull request merged**
